"""empty message

Revision ID: 92a89b24ab8b
Revises: 
Create Date: 2023-09-01 11:34:56.362899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a89b24ab8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anteced_salud',
    sa.Column('antecedente', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('antecedente')
    )
    op.create_table('ejercicios',
    sa.Column('ejercicio', sa.String(length=30), nullable=False),
    sa.Column('imagen_ejerc', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ejercicio')
    )
    op.create_table('musculos',
    sa.Column('musculo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('musculo')
    )
    op.create_table('musculo_ejercicio',
    sa.Column('pkfk_musculo', sa.String(length=30), nullable=False),
    sa.Column('pkfk_ejercicio', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['pkfk_ejercicio'], ['ejercicios.ejercicio'], ),
    sa.ForeignKeyConstraint(['pkfk_musculo'], ['musculos.musculo'], ),
    sa.PrimaryKeyConstraint('pkfk_musculo', 'pkfk_ejercicio')
    )
    op.create_table('usuarios',
    sa.Column('id_user', sa.BigInteger(), nullable=False),
    sa.Column('fk_tipo_user', sa.Enum('Administrador', 'Aprendiz', 'Instructor', name='tipos_usuarios'), nullable=True),
    sa.Column('nom1_user', sa.String(length=30), nullable=False),
    sa.Column('nom2_user', sa.String(length=30), nullable=True),
    sa.Column('ape1_user', sa.String(length=30), nullable=False),
    sa.Column('ape2_user', sa.String(length=30), nullable=True),
    sa.Column('correo_sena_user', sa.String(length=80), nullable=False),
    sa.Column('contrasena', sa.String(length=80), nullable=False),
    sa.Column('fk_anteced_salud_sel', sa.String(length=80), nullable=True),
    sa.Column('anteced_salud_inp', sa.String(length=255), nullable=True),
    sa.Column('estado_user', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_anteced_salud_sel'], ['anteced_salud.antecedente'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('anuncios',
    sa.Column('id_anunc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_id_admin_anunc', sa.BigInteger(), nullable=True),
    sa.Column('titulo_anunc', sa.String(length=60), nullable=False),
    sa.Column('desc_anunc', sa.String(length=255), nullable=False),
    sa.Column('img_anunc', sa.String(length=255), nullable=False),
    sa.Column('estado_anunc', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_id_admin_anunc'], ['usuarios.id_user'], ),
    sa.PrimaryKeyConstraint('id_anunc')
    )
    op.create_table('asistencia',
    sa.Column('id_registro_asis', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_instruc_asis', sa.BigInteger(), nullable=False),
    sa.Column('fk_id_aprend_asis', sa.BigInteger(), nullable=True),
    sa.Column('fecha_asis', sa.Date(), nullable=False),
    sa.Column('estado_asis', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_id_aprend_asis'], ['usuarios.id_user'], ),
    sa.PrimaryKeyConstraint('id_registro_asis')
    )
    op.create_table('planificador',
    sa.Column('id_reg_planif', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_id_aprend', sa.BigInteger(), nullable=True),
    sa.Column('fk_musculo', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['fk_id_aprend'], ['usuarios.id_user'], ),
    sa.ForeignKeyConstraint(['fk_musculo'], ['musculos.musculo'], ),
    sa.PrimaryKeyConstraint('id_reg_planif')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planificador')
    op.drop_table('asistencia')
    op.drop_table('anuncios')
    op.drop_table('usuarios')
    op.drop_table('musculo_ejercicio')
    op.drop_table('musculos')
    op.drop_table('ejercicios')
    op.drop_table('anteced_salud')
    # ### end Alembic commands ###
